serviceAccount:
  create: true
  name: aws-alb-ingress-controller-sa
  annotations:
    eks.amazonaws.com/role-arn:  "arn:aws:iam::${account_id}:role/${cluster_name}-alb-controller"

clusterName: ${cluster_name}
vpcId: ${vpc_id}
replicaCount: 1
region: ${aws_region}
resources:
  requests:
    cpu: ${alb_resources.cpu_request}
    memory: ${alb_resources.mem_request}
