autoDiscovery:
  clusterName: ${cluster_name}

awsRegion: ${aws_region}

# priorityClassName -- priorityClassName
priorityClassName: ""

rbac:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::${account_id}:role/${cluster_name}-autoscaler"
    name: "cluster-autoscaler-controller-sa"

# replicaCount -- Desired number of pods
replicaCount: 1

## Are you using Prometheus Operator?
# serviceMonitor:
#   namespace: prometheus
