aws:
  region: "${aws_region}"

## Limit possible target zones by domain suffixes (optional)
##
domainFilters:
  %{ for domain in ext_dns_domains }
  - ${domain}
  %{ endfor }

policy: sync

registry: "txt"
## TXT Registry Identifier
##
txtOwnerId: "${txtOwnerId}"

serviceAccount:
  name: "external-dns"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${account}:role/${cluster_id}-extDNS"

livenessProbe:
  httpGet:
    path: /healthz
    port: http

readinessProbe:
  httpGet:
    path: /healthz
    port: http

metrics:
  enabled: true
