apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: platform-nodeclass
spec:
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${CLUSTER_NAME}
        type: private

  securityGroupSelectorTerms:
    - id: ${NODE_SECURITY_GROUP_ID}

  instanceProfile: ${INSTANCE_PROFILE_NAME}

  amiSelectorTerms:
    - alias: al2@latest

  tags:
    nodeclass: platform-nodeclass

  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required

  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: ${NODE_VOLUME_SIZE}
        volumeType: ${NODE_VOLUME_TYPE}
        encrypted: ${NODE_ENCRYPTION_ENABLED}
        iops: ${NODE_IOPS}
        deleteOnTermination: true
        throughput: 125
