apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: external-secret-cluster-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${aws_region}
      auth:
        jwt:
          serviceAccountRef:
            name: "external-secrets-irsa"
            namespace: ${namespace}