apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${cluster_name}-cluster-secret"
  namespace: argocd
spec:
  secretStoreRef:
    name: external-secret-parameter-store
    kind: ClusterSecretStore
  target:
    name: "${cluster_name}-cluster-secret"
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
      data:
        name: "${cluster_name}"
        server: {{ .clusterEndpoint | toString }}
        config: |
          {
            "awsAuthConfig": {
                "clusterName": "${cluster_name}",
                "roleARN": "${argocd_client_role}"
            },
            "tlsClientConfig": {
              "caData": {{ .clusterCertificateData | toString }}
            }
          }
  data:
  - secretKey: clusterCertificateData
    remoteRef:
      key: "${aws_parameter}/clusterCertificateData"
  - secretKey: clusterEndpoint
    remoteRef:
      key: "${aws_parameter}/clusterEndpoint"