apiVersion: v1
kind: Secret
metadata:
  name: "${cluster_name}-cluster-secret"
  namespace: ${namespace}
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: "${cluster_name}"
  server: ${cluster_endpoint}
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }