apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${repo_config_name}
  namespace: argocd
spec:
  secretStoreRef:
    name: external-secret-parameter-store
    kind: ClusterSecretStore
  target:
    name: ${repo_config_name}
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: ${github_url}
        sshPrivateKey: |
          {{ .sshPrivateKey | toString }}
  data:
  - secretKey: sshPrivateKey
    remoteRef:
      key: ${aws_parameter}