apiVersion: v1
kind: Secret
metadata:
  name: ${repo_config_name}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io

type: Opaque
data:
  sshPrivateKey: ${github_sshkey}
  type: Z2l0
  url: ${github_url}
