apiVersion: 1
datasources:
- name: Tempo
  type: tempo
  access: proxy
  url: "http://${tempo_svc}:3100"
  version: 1
  isDefault: false
  jsonData:
    serviceMap:
      datasourceUid: 'prometheus'
    nodeGraph:
      enabled: true
    search:
      hide: false
    traceQuery:
      timeShiftEnabled: true
      spanStartTimeShift: '1h'
      spanEndTimeShift: '-1h'